# Generated by Django 5.1 on 2024-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_user_attached_files_user_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='connected_persons',
            field=models.JSONField(blank=True),
        ),
    ]
