# Generated by Django 5.1 on 2024-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_alter_user_connected_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attached_files',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patriot_details',
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='news_screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_details',
            field=models.JSONField(blank=True, default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='social_media_screenshots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
